### ISSUE TITLE
Docs not compiling automatically from main branch

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#24]
It looks like the docs are not compiling automatically from the main branch after a push from a PR.

I believe we need to add something like
``` yml
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
```
